# -*- coding: utf-8 -*-
"""Welcome_to_Colaboratory (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msKzcRz5uCdQylu1IxgzlMJVw98uRsjb
"""

from google.colab import drive
drive.mount('/content/drive')

weather_api_key = "9d7cde1f6d07ec55650544be1631307e"